=========             - implemented algorithm that random speedlimit follows user speed             - implemented feature that it will check the speedlimit from overpass API first, if returns null then go random             - implemented asyn task to separate jobs of updating speedlimit and color of textview and voice             - Use textview's value for checking speed limit vs current speed because the change of textview and the change of values are not at the same time that it does not speech and change textview at the same time"
            Error: Algorithm that changes the speedlimits by user current speed are design for better demo using build in location testing from Virtual machine.
            However, it would not shows the approching speedlimit and at the speedlimit both in colors and speech.
            Only below speedlimit and speeding would be shown and speech.